name: Push

on:
  push:
    branches:
      - 'main_v2'
  workflow_dispatch:
  repository_dispatch:
    types: [ost-data-push-direct]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run main_quick_test.py
      run: |
        git clone https://github.com/BA-OST-Index/ost_data.git data
        mkdir -p data_export
        python main_quick_test.py
    - name: Generator Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTION_SCRIPT }}
        event-type: ost-data-parser-push-direct
        repository: BA-OST-Index/ost_data_site_generator