name: Push

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # 获取子模块的代码
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Run main.py
      run: python main.py
    - name: Push changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        cd data_export
        git add .
        git commit -m "Update: ${{ github.event.head_commit.message }}"
        git push origin HEAD:main