name: Push

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Update submodules
      run: |
        git submodule update --remote
    - name: Run main.py
      run: python main.py
    - name: Push changes
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"
        cd ost_data_export
        git config --unset-all http.https://github.com/.extraheader
        git add .
        git commit -m "Update: ${{ github.event.head_commit.message }}"
        git push https://github-actions[bot]:$REPO_KEY@github.com/BA-OST-Index/ost_data_export.git HEAD:main
      env:
        REPO_KEY: ${{secrets.ACTION_SCRIPT}}